"""
LeRobot v2.1 feature schema and modality config for the AgiBot X2 Ultra
SONIC VLA pipeline.

Schema design summary
---------------------

The X2 dataset writes a single concatenated proprioception vector
``observation.state`` of shape ``(num_body_joints + 2 * hand_dof,)`` =
``(31 + 20,)`` = ``(51,)`` for the ``omnihand_10`` variant. The body
slice is laid out in Pinocchio's URDF parse order (driven by the X2
``RobotModel``); the hand slice is appended after the body and is
out-of-band (the X2 URDF does not contain finger joints, so hand
positions come from the AimDK HAL via the ``hand_joints`` field of
the C++ deploy's ``x2_debug`` ZMQ topic).

Action space mirrors ``unitree_g1_sonic`` for cross-embodiment compat:
``action.motion_token`` (64-D SONIC latent) plus
``action.left_hand_joints`` / ``action.right_hand_joints`` (10-D each
in the OmniHand variant, or 7-D when used with the G1-compatible
modality config). The 10-DOF dataset can be down-projected to 7-DOF
on the fly during training via the modality registry alias loaded
through ``--modality-config-path``.

Reference: ``docs/source/references/x2_isaac_groot_data_contract.md``.
"""

from __future__ import annotations

from typing import Literal

import numpy as np

from gear_sonic.data.robot_model import RobotModel


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

EGO_VIEW_HEIGHT: int = 480
"""Ego-view image height (pixels). Matches the AimDK head RGB-D camera."""

EGO_VIEW_WIDTH: int = 640
"""Ego-view image width (pixels)."""

FPS: int = 50
"""Dataset frame rate. Matches the SONIC tracking-policy control rate
and the upstream ``unitree_g1_sonic`` reference."""

SONIC_MOTION_TOKEN_DIM: int = 64
"""SONIC latent motion-token dimensionality (frozen 22k checkpoint)."""

HAND_DOF_OMNI: int = 10
"""Per-side OmniHand DOF count (matches agitbot-x2-record-and-replay)."""

HAND_DOF_G1_COMPAT: int = 7
"""Per-side hand DOF count when down-projected to the G1 ThreeFinger surface."""


# Body-joint groups exposed to the modality config. Order matters: the
# groups are projected into ``observation.state`` slices via the
# RobotModel's joint-group indices, and the trainer attends to *these*
# group names (not the head). Head DOFs remain present in
# ``observation.state`` for completeness but are not surfaced as a
# state group, mirroring ``unitree_g1_sonic`` (which has no head).
_BODY_JOINT_GROUPS: tuple[str, ...] = (
    "left_leg",
    "right_leg",
    "waist",
    "left_arm",
    "right_arm",
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def get_x2_robot_model(
    hand_variant: Literal["omnihand_10", "g1_compat_7"] = "omnihand_10",
) -> RobotModel:
    """Instantiate the X2 Ultra ``RobotModel`` for VLA dataset assembly.

    Args:
        hand_variant: ``"omnihand_10"`` (default, v0 target) or
            ``"g1_compat_7"`` for cross-embodiment evaluation.

    Returns:
        Pinocchio-backed ``RobotModel`` exposing the 31 body DOFs through
        ``joint_to_dof_index`` plus the side-loaded finger names via
        ``supplemental_info.left_finger_names`` / ``right_finger_names``.
    """
    from gear_sonic.data.robot_model.instantiation.x2_ultra import (
        instantiate_x2_ultra_robot_model,
    )

    return instantiate_x2_ultra_robot_model(hand_variant=hand_variant)


def _get_body_group_slices(robot_model: RobotModel) -> dict[str, dict[str, int]]:
    """Project each body joint group into a contiguous ``observation.state`` slice.

    Group indices are pulled directly from Pinocchio (URDF parse order). Each
    group must be contiguous in DOF index space -- this is the case for X2's
    body URDF (legs/waist/arms/head are laid out in blocks). The returned
    dict has the exact shape that ``meta/modality.json`` expects.
    """
    slices: dict[str, dict[str, int]] = {}
    for group in _BODY_JOINT_GROUPS:
        indices = sorted(robot_model.get_joint_group_indices(group))
        if indices != list(range(indices[0], indices[-1] + 1)):
            raise ValueError(
                f"Joint group '{group}' is not contiguous in DOF index space: "
                f"{indices}. Update the URDF or split the group."
            )
        slices[group] = {
            "start": indices[0],
            "end": indices[-1] + 1,
            "original_key": "observation.state",
        }
    return slices


def assemble_observation_state(
    robot_model: RobotModel,
    body_q: np.ndarray,
    left_hand_q: np.ndarray,
    right_hand_q: np.ndarray,
) -> np.ndarray:
    """Concatenate body + hand joint positions into a single proprio vector.

    The layout matches the slices generated by :func:`get_modality_config_x2_vla`:
    ``[body_31][left_hand_10][right_hand_10]`` for the ``omnihand_10`` variant.

    Args:
        robot_model: X2 ``RobotModel`` instance (used for body sizing only).
        body_q: 1-D body configuration of shape ``(num_body_joints,)`` in
            Pinocchio URDF order. Equivalent to
            ``robot_model.get_configuration_from_actuated_joints(body_q,
            left_hand_actuated_joint_values=[], right_hand_actuated_joint_values=[])``
            but skips the empty-hand round-trip.
        left_hand_q: 1-D vector of left-hand joint angles (typically 10).
        right_hand_q: 1-D vector of right-hand joint angles (matches ``left_hand_q``).

    Returns:
        1-D ``float64`` array of shape ``(num_body_joints + len(left_hand_q) + len(right_hand_q),)``.
    """
    body_q = np.asarray(body_q, dtype=np.float64).reshape(-1)
    if body_q.shape[0] != robot_model.num_joints:
        raise ValueError(
            f"body_q has {body_q.shape[0]} dims; expected "
            f"robot_model.num_joints={robot_model.num_joints}"
        )
    left = np.asarray(left_hand_q, dtype=np.float64).reshape(-1)
    right = np.asarray(right_hand_q, dtype=np.float64).reshape(-1)
    return np.concatenate([body_q, left, right])


# ---------------------------------------------------------------------------
# Feature schema (meta/info.json -> "features")
# ---------------------------------------------------------------------------


def get_features_x2_vla(
    robot_model: RobotModel,
    hand_dof_per_side: int = HAND_DOF_OMNI,
) -> dict:
    """Return the LeRobot v2.1 ``features`` dict for the X2 SONIC dataset."""
    body_joint_names = robot_model.joint_names
    num_body = robot_model.num_joints

    if hand_dof_per_side not in (HAND_DOF_OMNI, HAND_DOF_G1_COMPAT):
        raise ValueError(
            f"hand_dof_per_side must be {HAND_DOF_OMNI} or {HAND_DOF_G1_COMPAT}; "
            f"got {hand_dof_per_side}."
        )

    finger_names_left = (
        robot_model.supplemental_info.left_finger_names
        if hasattr(robot_model.supplemental_info, "left_finger_names")
        else [f"left_finger_{i}" for i in range(hand_dof_per_side)]
    )
    finger_names_right = (
        robot_model.supplemental_info.right_finger_names
        if hasattr(robot_model.supplemental_info, "right_finger_names")
        else [f"right_finger_{i}" for i in range(hand_dof_per_side)]
    )

    state_dim = num_body + 2 * hand_dof_per_side
    state_names = list(body_joint_names) + list(finger_names_left) + list(finger_names_right)

    return {
        "observation.images.ego_view": {
            "dtype": "video",
            "shape": [EGO_VIEW_HEIGHT, EGO_VIEW_WIDTH, 3],
            "names": ["height", "width", "channel"],
        },
        "observation.state": {
            "dtype": "float64",
            "shape": (state_dim,),
            "names": state_names,
        },
        "observation.projected_gravity": {
            "dtype": "float64",
            "shape": (3,),
            "names": ["gravity_x", "gravity_y", "gravity_z"],
        },
        "action.motion_token": {
            "dtype": "float64",
            "shape": (SONIC_MOTION_TOKEN_DIM,),
            "names": [f"motion_token_{i}" for i in range(SONIC_MOTION_TOKEN_DIM)],
        },
        "action.left_hand_joints": {
            "dtype": "float64",
            "shape": (hand_dof_per_side,),
            "names": list(finger_names_left),
        },
        "action.right_hand_joints": {
            "dtype": "float64",
            "shape": (hand_dof_per_side,),
            "names": list(finger_names_right),
        },
    }


# ---------------------------------------------------------------------------
# Modality config (meta/modality.json)
# ---------------------------------------------------------------------------


def get_modality_config_x2_vla(
    robot_model: RobotModel,
    hand_dof_per_side: int = HAND_DOF_OMNI,
) -> dict:
    """Return the ``meta/modality.json`` content for the X2 SONIC dataset.

    Trainer-visible state groups mirror ``unitree_g1_sonic``:
    ``left_leg``, ``right_leg``, ``waist``, ``left_arm``, ``right_arm``,
    ``left_hand``, ``right_hand``, ``projected_gravity``. Head DOFs live
    in ``observation.state`` for completeness but are not exposed as a
    state group (matches G1).

    Action surface uses three keys to match ``unitree_g1_sonic``:
    ``motion_token`` (64), ``left_hand_joints`` (10 or 7), ``right_hand_joints`` (10 or 7).
    """
    if hand_dof_per_side not in (HAND_DOF_OMNI, HAND_DOF_G1_COMPAT):
        raise ValueError(
            f"hand_dof_per_side must be {HAND_DOF_OMNI} or {HAND_DOF_G1_COMPAT}; "
            f"got {hand_dof_per_side}."
        )

    num_body = robot_model.num_joints
    body_slices = _get_body_group_slices(robot_model)

    hand_slices = {
        "left_hand": {
            "start": num_body,
            "end": num_body + hand_dof_per_side,
            "original_key": "observation.state",
        },
        "right_hand": {
            "start": num_body + hand_dof_per_side,
            "end": num_body + 2 * hand_dof_per_side,
            "original_key": "observation.state",
        },
    }

    return {
        "state": {
            **body_slices,
            **hand_slices,
            "projected_gravity": {
                "start": 0,
                "end": 3,
                "original_key": "observation.projected_gravity",
            },
        },
        "action": {
            "motion_token": {
                "start": 0,
                "end": SONIC_MOTION_TOKEN_DIM,
                "original_key": "action.motion_token",
            },
            "left_hand_joints": {
                "start": 0,
                "end": hand_dof_per_side,
                "original_key": "action.left_hand_joints",
            },
            "right_hand_joints": {
                "start": 0,
                "end": hand_dof_per_side,
                "original_key": "action.right_hand_joints",
            },
        },
        "video": {
            "ego_view": {"original_key": "observation.images.ego_view"},
        },
        "annotation": {
            "human.task_description": {"original_key": "task_index"},
        },
    }


__all__ = [
    "EGO_VIEW_HEIGHT",
    "EGO_VIEW_WIDTH",
    "FPS",
    "HAND_DOF_G1_COMPAT",
    "HAND_DOF_OMNI",
    "SONIC_MOTION_TOKEN_DIM",
    "assemble_observation_state",
    "get_features_x2_vla",
    "get_modality_config_x2_vla",
    "get_x2_robot_model",
]
