#!/usr/bin/env bash
RUN_STAMP="${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}"
# Per-run log stamp. These paths used to be FROZEN at 20260716_141256,
# so every run since appended into one directory -- 152 MB of interleaved
# runs with no boundaries, making A/B comparison of tuning configs
# impossible. Override RUN_STAMP to group a set of runs deliberately.

# autogenerated by x2_pc2_daemons.sh for tmux session: x2_pose_watchdog
# regenerated on every 'start'; edit the daemon script, not this file
_keep_alive() {
    local rc=$?
    echo
    echo "[tmux-launch] cmd exited with status=${rc}"
    if [[ "${rc}" -ne 0 ]]; then
        echo "[tmux-launch] NON-ZERO EXIT -- inspect scrollback above for the real error."
    fi
    echo "[tmux-launch] keeping pane alive (read scrollback above; Ctrl-D to close)"
    exec bash -l
}
trap _keep_alive EXIT
echo "[tmux-launch] session=${TMUX_PANE:-?} pid=$$"
echo "[tmux-launch] starting at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "[tmux-launch] ---- daemon body ----"
source /opt/ros/humble/setup.bash &&         export AMENT_PREFIX_PATH=/agibot/software/housekeeper/bin/aimdk_msgs:$AMENT_PREFIX_PATH &&         export LD_LIBRARY_PATH=/agibot/software/housekeeper/bin/aimdk_msgs/lib:$LD_LIBRARY_PATH &&         source /home/run/getsolo/ws/install/setup.bash &&         export LD_LIBRARY_PATH=/home/run/getsolo/onnxruntime/lib:$LD_LIBRARY_PATH &&         export PYTHONPATH=/agibot/software/housekeeper/bin/aimdk_msgs/local/lib/python3.10/dist-packages:/home/run/getsolo/ws/src:${PYTHONPATH:-} &&             /home/run/getsolo/venv/bin/python3 /home/run/getsolo/gear_sonic_deploy/scripts/x2_pose_watchdog.py                 --upstream-host 127.0.0.1                 --upstream-port 5556                 --upstream-topic pose                 --downstream-port 5558                 --downstream-topic pose                 --idle-x2m2 /home/run/getsolo/data/idle_stand.x2m2                 --idle-stale-ms 100                 --idle-mode blend                 --hold-last-secs 0.05                 --blend-secs 0.15                 --x2-debug-port 5557                 2>&1 | tee -a /home/run/getsolo/log/pose_watchdog_${RUN_STAMP}.log

