#!/usr/bin/env bash
# PC2-resident deploy launcher for GAMEPAD RITUAL ignition. Checked into the
# repo at x2_pc2/ and staged to /home/run/getsolo/ by pc2_bringup.sh.
#
# WHY THIS FILE EXISTS (2026-07-29 blocked-ignition incident):
# the ritual scripts used to launch the deploy via log/start_x2_deploy.sh,
# which x2_pc2_daemons.sh REGENERATES from the laptop on every `start` with
# whatever flags that session used. A tethered session that omitted
# --no-confirm left a body behind whose deploy sat forever at the
# "Stop MC and launch policy? [y/N]" gate inside a detached tmux pane --
# unanswerable from a gamepad. The robot's ignition path must never depend
# on what the last laptop command happened to be.
#
# SAFETY: --no-confirm is baked in HERE, and only here, because on this
# path the operator confirmation is the ritual chord (L1+L2+R1+R2+Y,
# deliberately hard to press by accident) plus the pose-stream gate the
# ritual scripts run before this file is allowed to execute. Laptop-driven
# starts via x2_pc2_daemons.sh keep their interactive y/N gate.
#
# Arg set mirrors the 2026-07-28 hardware-verified deploy body, minus
# --vla-resume-host (that's the laptop/Quest3 SAFE_IDLE resume PUB; empty
# disables the socket, and the deploy still self-exits SAFE_IDLE on the
# first non-stale pose frame -- no laptop involved).
#
# Overridables (env), defaults = current deployed state:
#   X2_RITUAL_MODEL    sonic ONNX      (default policies/agibot_x2_sonic.onnx)
#   X2_RITUAL_TUNING   tuning YAML     (default walking_soft_kp.yaml)
#
# TUNING DEFAULT = walking_soft_kp.yaml, the config every captured
# successful robot run used (9/9 in docs/experiments/robot_runs/). The
# 2026-07-29 waist-wobble incident (battery pull) ran the launcher's
# original default, walking_recovery_loose.yaml -- inherited blindly from
# the previous night's laptop session body. recovery_loose is soft_kp's
# ANCESTOR: waist_pr kp 2.81 (vs 2.00) and untrimmed kd, i.e. the exact
# action-jump-times-kp slam mode soft_kp's header documents. The ritual
# default must be the ritual-proven config, never whatever a laptop
# experiment last used.

PREFIX=/home/run/getsolo
MODEL="${X2_RITUAL_MODEL:-${PREFIX}/policies/agibot_x2_sonic.onnx}"
TUNING="${X2_RITUAL_TUNING:-${PREFIX}/gear_sonic_deploy/configs/real_deploy_tuning/walking_soft_kp.yaml}"
LOG_DIR="${PREFIX}/log/deploy_ritual_$(date +%Y%m%d_%H%M%S)"

# Same post-mortem trap as the autogenerated bodies: keep the tmux pane
# attachable after a crash so the traceback survives `tmux attach`.
_keep_alive() {
    local rc=$?
    echo
    echo "[ritual-launch] cmd exited with status=${rc}"
    if [[ "${rc}" -ne 0 ]]; then
        echo "[ritual-launch] NON-ZERO EXIT -- inspect scrollback above for the real error."
    fi
    echo "[ritual-launch] keeping pane alive (read scrollback above; Ctrl-D to close)"
    exec bash -l
}
trap _keep_alive EXIT
echo "[ritual-launch] pid=$$ model=${MODEL}"
echo "[ritual-launch] tuning=${TUNING}"
echo "[ritual-launch] log_dir=${LOG_DIR}"
echo "[ritual-launch] starting at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "[ritual-launch] ---- deploy body (--no-confirm: ritual chord + pose gate are the operator confirmation) ----"

cd "${PREFIX}/gear_sonic_deploy" && \
    "${PREFIX}/gear_sonic_deploy/deploy_x2.sh" onbot --no-docker --vla \
        --vla-zmq-host localhost --vla-zmq-port 5558 --vla-zmq-topic pose \
        --vla-debug-port 5557 --vla-debug-topic x2_debug \
        --wrist-bypass ik \
        --model "${MODEL}" \
        --log-dir "${LOG_DIR}" \
        --onbot-prefix "${PREFIX}" \
        --onbot-ws "${PREFIX}/ws" \
        --onbot-venv "${PREFIX}/venv" \
        --onbot-onnxruntime "${PREFIX}/onnxruntime" \
        --onbot-aimdk-prefix /agibot/software/housekeeper/bin/aimdk_msgs \
        --deploy-extra-arg --disable-pose-ref-watchdog \
        --tuning-config "${TUNING}" \
        --max-target-dev-head 0.01 \
        --no-confirm
